<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
?>
<div class="well" style="padding: 8px 0;">   
    <ul class="nav nav-list">
        <li class="nav-header">Quick Actions</li>
      	<li class="active"><a href="#">TBD</a></li>		
        <li class="divider"></li>
        <li><a href="#">TBD</a></li>    
    </ul>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
