<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	
?>
<div class="slideshow" style="background-position: center top; background-repeat: no-repeat; width:100%; height:500px; position:absolute; top:110px; z-index:-20;">
	<?php 
		for($i=1; $i<=8; $i++){
	?>
		<img style="opacity:0.5;" src="<?php echo $this->baseUrl("images/custom/".$i.".jpg"); ?>" />
	<?php } ?>
    <div class="xnav"><a id="prev2" href="#">Prev</a> <a id="next2" href="#">Next</a></div>
</div>
