<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Quick Help";
	$this->headTitle($this->translate("appname")." | ".$title); 

?>
<div class="row marginleft0">
    <div class="span8 pull-left marginleft0 public_leftcolumn">
        <div class="content">
            <h1><?php echo $title; ?></h1> 
            <p>Coming soon</p>
        </div>
    </div>
    <?php require APPLICATION_PATH."/views/scripts/index/righthandband.phtml"; ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
