<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "About ".$this->translate("appname");
	$this->headTitle($this->translate("appname")." | About"); 

?>
<div class="row marginleft0">
    <div class="span8 pull-left marginleft0 public_leftcolumn">
        <div class="content">
        	<h1><?php echo $title; ?></h1>
            
            
          
        </div>
    </div>
    <?php require APPLICATION_PATH."/views/scripts/index/righthandband.phtml"; ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
