<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

Dear <?php echo $this->firstname; ?>,<br /><br />

You recently requested to change your <?php echo $this->appname; ?> Email Address to '<?php echo $this->toemail; ?>'.<br /><br />

To confirm this request, you will have to enter the activation key below under account settings:<br />

Code: <?php echo $this->code; ?><br /><br />

Alternatively, click on the activation link below:<br />

<?php echo $this->activationurl; ?><br /><br />

If the page fails to open, copy the activation link and paste it in the address window of the browser.<br /><br />

On confirmation, you will no longer be able to login using '<?php echo $this->fromemail; ?>'.<br />

If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
            