<table style="width:700px; margin:0;">	
    <tr>
    	<td style="padding:0; margin:0;"><img class="header" src="<?php echo $this->serverUrl($this->baseUrl("images/emailhead.png")); ?>" /></td>
    </tr>
</table>
<table style="width:700px; margin:0; padding:25px 25px 25px 15px; background-color:#fafdff; font-family: Arial, Helvetica, Tahoma, sans-serif; font-size:15px; line-height: 1.2em;">    
    <tr>
    	<td>