<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
Dear <?php echo $this->firstname; ?>,<br /><br />

A request has been made for a new password for your <?php echo $this->appname; ?> Account. <br /><br />

You can set a new password by clicking on the link below:<br />
<?php echo $this->resetpasswordurl."\n"; ?><br /><br />

If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>