<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
Dear <?php echo $this->firstname; ?>,<br /><br />

We would like to welcome you to <?php echo $this->appname; ?>.<br /><br />

To activate your new <?php echo $this->appname; ?> account, click on the activation link below:<br />

<?php echo $this->activationurl; ?><?php // echo $this->serverUrl($this->url($this->activationurl)); ?><br /><br />

If the page fails to open, copy the activation link and paste it in the address window of the browser.<br />

After activating your account, you can login using the your email address and the password you provided.<br /><br />

If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
