<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Change Email";
	$this->headTitle($title); 
	
	$useraccount = new UserAccount(); 	
	$useraccount->populate(decode($request->id));
	// debugMessage($useraccount->toArray());
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$useraccount->processPost($session->getVar(FORM_VALUES));	
	}

	$this->headTitle($title);
?>
<script>
	$(document).ready(function() {		
		
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				email: {
					required: true, 
					email: true,
					new_not_old: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {				
				email: {
					required: "<?php echo $this->translate("useraccount_email_error"); ?>", 
					email: "<?php echo $this->translate("useraccount_email_invalid_error"); ?>",
					new_not_old: "New Email should be different from current one"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		$.validator.addMethod("new_not_old", function(value, element) {
			var old = $("#oldemail").val();
			if(old != "" && value == old){
				return false;
			}		
			return true
		}, "New Email should be different from current one");
		
		//when button is clicked  
        $('#check_email_availability').click(function(){ 
			check_email_availability();  
        });
		$('#email').change(function(){ 
			check_email_availability();  
        });  
		$('#email').keyup(function(){
			this.value = this.value.toLowerCase();
		});  
		
		//function to check email availability  
		function check_email_availability(){  
			//get the username
			var checking_html = 'Checking availability...';   
			var email = $('#email').val();  
			if(!isEmptyString(email) && validateEmail(email)){
				$('#email_availability_result').html(checking_html);  
				
				//use ajax to run the check  
				$.post("<?php echo $this->baseUrl('signup/checkemail'); ?>", { email: email },  
					function(result){  
						//if the result is 1  
						// alert(result); // return false;
						if(result == 1){  
							//show that the email is available
							$('#email_availability_result').html(email + ' is NOT available!').addClass('alert').addClass('alert-error').removeClass('alert-success'); 
						} else {  
							//show that the email is NOT available  
							$('#email_availability_result').html(email + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-error');
						}  
				});  
			}
		} 
		
	}); 
</script>
<div class="popupdiv">
<form class="form-horizontal well span6" id="indexform" method="post">
    <table class="table">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
		<tr>
            <td width="30%"><label class="control-label pull-left">Current Login Email: </label></td>
            <td><input name="oldemail" id="oldemail" type="hidden" value="<?php echo $useraccount->getEmail(); ?>" /><?php echo $useraccount->getEmail(); ?>
            	<input type="hidden" name="entityname" value="UserAccount" />
                <input type="hidden" id="id" name="id" value="<?php echo encode($useraccount->getID()); ?>" />
            </td>
        </tr>
        <tr>
            <td><label class="control-label pull-left">New Login Email: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input style="width:70%;" class="validate_255_string" name="email" id="email" type="text" value="<?php echo $useraccount->getEmail2(); ?>" />
            	<label class='lineblocked'><a href="javascript: void(0);" class="btn btn-primary btn-mini" id='check_user_availability' title="Check Availability">Check</a></label><div id="email_error"></div><div id="email_availability_result" style="margin-top:5px;"></div>
            </td>
        </tr>
	</table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>