<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Set page title
	$title = $this->translate("useraccount_pagetitle_changepassword_confirmation");
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	$this->headTitle($title); 
?>
<h1><?php echo $title; ?></h1>
<table>
	<tr>
        <td><label class="successmessage">You have successfully changed your password</label></td>
    </tr>
    <tr>
    	<td><br /><a href="<?php echo $this->baseUrl("user/logout");?>">Click here</a> to login using your new password</td>
    </tr>
</table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>