<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_recoverpassword");
	$this->headTitle($title);  
	
	$useraccount = new UserAccount(); 
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
	
?>
<script>
$(document).ready(function() {
	$("#logintable #email").focus();
	$("#logintable #loginform").validate({		
		// define the validation rules one field at a time
		rules: {
			email: {
				"required": true
			}
		}, 
		messages: {
			email: {
				"required": "<?php echo $this->translate("useraccount_credential_error"); ?>"
			}
		}
	}); 
	
}); 
</script>
<style>
.form-horizontal .control-label {
	text-align:left;
	font-family:'calibri','Telex',sans-serif;
	font-weight:normal;
	font-size:16px;
	margin-bottom:5px;
}
body.publicbody {
	background-image: none;
	background-color: #ebebeb;
}
body.publicbody #contentwrapper {
	background:none;
}
body.publicbody #contentcolumn {
	background:none;
}

</style>
<div id="logincontainer">
	<h1 class="calfont" style="font-weight:bold; font-size:20px; border-bottom:1px solid #bdbdbd; color:#333333; padding:5px;">Welcome Back to <?php echo $this->translate('appname'); ?></h1>
    <table style="width:100%; margin:0;">
    	<tr>
        	<td style="width:50%; vertical-align:top;">
            	<?php require APPLICATION_PATH."/views/scripts/user/leftwidget.phtml"; ?>
            </td>
            <td style="padding-left:15px; padding-top:0; vertical-align:top;">
            	<table id="logintable">
                	<tr>
                    	<td>
                        	<form class="form-horizontal" id="loginform" action="<?php echo $this->baseUrl('user/processrecoverpassword'); ?>" method="post">	
                               <table class="maxwidth noborder">
                                   <tr>
                                       <td><h3 class="calfont" style="font-size:18px; font-weight:normal; color:#3b3b3b; margin-top:10px;">Reset Account</h3></td>
                                   </tr>
                                   <?php if($sessionhaserror) { ?>
                                   <tr>			
                                       <td><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                                   </tr>
                                   <?php } ?>
                                   <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                                   <tr>			
                                       <td><div class="alert alert-success"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div></td>
                                   </tr>
                                   <?php } ?>
                                   <?php if(!$sessionhaserror && isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>          
                                   <tr>			
                                       <td>&nbsp;</td>
                                   </tr>
                                   <?php } ?>
                                   <?php if(!isEmptyString($request->redirecturl)){ ?>
                                   <tr>			
                                       <td style="padding-top:0; padding-bottom:0; height:20px;"><div style="padding:5px 5px;" class="alert alert-info margin0 centeralign">Please login to continue</div></td>
                                   </tr>
                                   <?php } ?>
                                   <tr>
                                       <td style="padding:10px 0;">
                                       		<label class="control-label pull-left" for="email">Identity: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                       		<input name="email" id="email" placeholder="Enter Username or Email or Phone" />
                                            <label class="pagedescription" style="font-size:11px;">e.g &nbsp; <span class="green">jdoe</span> &nbsp;or &nbsp;<span class="green">jdoe@domain.com</span> or <span class="green">0772445566</span></label>
                                       </td>
                                   </tr>
                                   <tr>
                                       <td style="padding:15px 0 10px 0;">
                                       		<button id="reset" class="btn btn-primary" type="submit" title="Reset Account"><i class="icon-lock icon-white"></i> Reset</button></td>
                                       
                                   </tr>                    
                               </table>
                            </form>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>