<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_recoverpassword_confirm"); 
	$this->headTitle($title); 
	
	// the usermaking the payment
	$useraccount = new UserAccount();
	
?>
<style>
.form-horizontal .control-label {
	text-align:left;
	font-family:'calibri','Telex',sans-serif;
	font-weight:normal;
	font-size:16px;
	margin-bottom:5px;
}
body.publicbody {
	background-image: none;
	background-color: #ebebeb;
}
body.publicbody #contentwrapper {
	background:none;
}
body.publicbody #contentcolumn {
	background:none;
}

</style>
<div id="logincontainer">
	<h1 class="calfont" style="font-weight:bold; font-size:20px; border-bottom:1px solid #bdbdbd; color:#333333; padding:5px;">Welcome Back to <?php echo $this->translate('appname'); ?></h1>
    <table style="width:100%; margin:0;">
    	<tr>
        	<td style="width:50%; vertical-align:top;">
            	<?php require APPLICATION_PATH."/views/scripts/user/leftwidget.phtml"; ?>
            </td>
            <td style="padding-left:15px; padding-top:0; vertical-align:top;">
            	<table id="logintable">
                	<tr>
                    	<td>
                        	<form class="form-horizontal" id="loginform" action="" method="post">	
                               <table class="maxwidth noborder">
                                   <tr>
                                       <td><h3 class="calfont" style="font-size:18px; font-weight:normal; color:#3b3b3b; margin-top:10px;"><?php echo $title; ?></h3></td>
                                   </tr>
                                   <?php if($sessionhaserror) { ?>
                                   <tr>			
                                       <td><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                                   </tr>
                                   <?php } ?>
                                   <tr>			
                                       <td>&nbsp;</td>
                                   </tr>
                                   <tr>			
                                       <td><div class="alert alert-success">Reset instructions sent successfully</div></td>
                                   </tr>
                                   <tr>
                                        <td>An email has been sent to you with instructions on how to reset your password. If you don't see the email in your inbox, please check your <b>Junk</b> or <b>Spam</b> mail folder.<br /><br />		
                                        
                                        For any assistance please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />
                                        </td>
                                    </tr>           
                               </table>
                            </form>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>