<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_resetpassword");
	$this->headTitle($title);  
	
	$useraccount = new UserAccount(); 
	$id = $request->id;
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
	
?>
<script>
$(document).ready(function() {
	$("#email").focus();
	$("#loginform").validate({		
		// define the validation rules one field at a time
		rules: {
			password: {
				required: true,
				maxlength: <?php echo $config->password->maxlength; ?>,
				minlength: <?php echo $config->password->minlength; ?>
			},			
			confirmpassword: {
				required: true,
				equalTo: "#password"
			}
		}, 
		messages: {
			password: {
				required: "<?php echo $this->translate("useraccount_password_error"); ?>",
				maxlength: "<?php echo sprintf($this->translate("useraccount_password_error_maxlength"), $config->password->maxlength); ?>",
				minlength: "<?php echo sprintf($this->translate("useraccount_password_error_minlength"), $config->password->minlength); ?>"					
			},
			confirmpassword: {
				required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
				equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
			}
		}
	}); 
}); 
</script>
<style>
.form-horizontal .control-label {
	text-align:left;
	font-family:'calibri','Telex',sans-serif;
	font-weight:normal;
	font-size:16px;
	margin-bottom:5px;
}
body.publicbody {
	background-image: none;
	background-color: #ebebeb;
}
body.publicbody #contentwrapper {
	background:none;
}
body.publicbody #contentcolumn {
	background:none;
}

</style>
<div id="logincontainer">
	<h1 class="calfont" style="font-weight:bold; font-size:20px; border-bottom:1px solid #bdbdbd; color:#333333; padding:5px;">Welcome Back to <?php echo $this->translate('appname'); ?></h1>
    <table style="width:100%; margin:0;">
    	<tr>
        	<td style="width:50%; vertical-align:top;">
            	<?php require APPLICATION_PATH."/views/scripts/user/leftwidget.phtml"; ?>
            </td>
            <td style="padding-left:15px; padding-top:0; vertical-align:top;">
            	<table id="logintable">
                	<tr>
                    	<td>
                        	<form class="form-horizontal" id="loginform" action="<?php echo $this->baseUrl('user/processresetpassword'); ?>" method="post">	
                               <table class="maxwidth noborder">
                                   <tr>
                                       <td><h3 class="calfont" style="font-size:18px; font-weight:normal; color:#3b3b3b; margin-top:10px;"><?php echo $title; ?></h3></td>
                                   </tr>
                                   <?php if($sessionhaserror) { ?>
                                   <tr>			
                                       <td><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                                   </tr>
                                   <?php } ?>
                                   <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                                   <tr>			
                                       <td><div class="alert alert-success"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div></td>
                                   </tr>
                                   <?php } ?>
                                   <?php if(!$sessionhaserror && isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>          
                                   <tr>			
                                       <td>&nbsp;</td>
                                   </tr>
                                   <?php } ?>
                                   <tr>
                                       <td style="padding:10px 0;">
                                       		<label class="control-label" for="email"><?php echo $this->translate("useraccount_password_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                       		<input name="password" id="password" type="password" placeholder="Enter new Password" title="" />
                                       </td>
                                   </tr>
                                   <tr>
                                       <td style="padding:10px 0;">
                                       		<label class="control-label" for="email"><?php echo $this->translate("useraccount_password_confirm_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                       		<input name="confirmpassword" id="confirmpassword" type="password" placeholder="Confirm Password" />
                                       </td>
                                   </tr>
                                   <tr>
                                       <td style="padding:15px 0 10px 0;">
                                       		<button id="reset" class="btn btn-primary xbtn-large" type="submit" title="Save Password"><i class="icon-lock icon-white"></i> Save Password</button><input name="id" type="hidden" value="<?php echo $id; ?>" />
                                       </td>
                                   </tr>
                               </table>
                            </form>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>